### ISSUE TITLE
Question sur ce projet 

### ISSUE THREAD

**Issue by BornTKill** [ssenart/ha-custom_components#1]
Bonjour,

Ce repo a t il vocation de remplacer les branches veolia et gazpar de ton repo Ha ?

J’utilise tes composants depuis un moment et ils ne fonctionne plus actuellement. Je ne saurai dire depuis quand. Je suis en 0.116.4

Bien à toi.

**Comment by ssenart** [comment]
Bonjour,Oui, en effet, je maintiens ce projet et abandonne les branches HA. Les sites Veolia et Grdf ont fait des petits changements, ces dernières semaines, qui ont nécessité des ajustements dans les libraires PyGazpar et PyVeoliaIDF. A chaque fois, il faut mettre à jour le manifest des composants HA correspondants.En prenant la dernière de master, cela devrait corriger tes problèmes. Dis-moi si ce n'est pas le cas.Cordialement,Stéphane PS: je suis en 0.115.2.
-------- Message d'origine --------De : BornTKill <notifications@github.com> Date : 19/10/2020  21:45  (GMT+01:00) À : ssenart/ha-custom_components <ha-custom_components@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [ssenart/ha-custom_components] Question sur ce projet  (#1) 

Bonjour,

Ce repo a t il vocation de remplacer les branches veolia et gazpar de ton repo Ha ?

J’utilise tes composants depuis un moment et ils ne fonctionne plus actuellement. Je ne saurai dire depuis quand. Je suis en 0.116.4

Bien à toi.
